# Generated by Django 3.0.6 on 2020-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0004_auto_20200530_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='moves_list',
            new_name='movesList',
        ),
    ]
