# Generated by Django 3.0.6 on 2020-06-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0005_auto_20200604_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='movesList',
            new_name='moveList',
        ),
    ]
