# Generated by Django 3.0.6 on 2020-06-08 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0006_auto_20200608_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='setList',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
