# Generated by Django 3.0.6 on 2020-06-14 22:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0007_userprofile_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='probabilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
