# Generated by Django 3.0.6 on 2020-06-15 02:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0008_userprofile_probabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='probabilities',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='probs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='moveList',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setList',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
