# Generated by Django 3.0.6 on 2020-06-17 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0008_auto_20200617_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='probs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
