# Generated by Django 3.0.6 on 2020-07-06 08:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0009_userprofile_probs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='durations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
