# Generated by Django 3.0.6 on 2020-07-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0010_userprofile_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userId',
            field=models.CharField(default='hello', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
