# Generated by Django 3.0.7 on 2020-07-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboyapp', '0011_auto_20200717_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
